FROM nginx:alpine
LABEL maintainer="Wolfgang Schiffels<wolfgang.schiffels@baqend.com>"

RUN rm /etc/nginx/conf.d/default.conf \
    && mkdir -p /var/www/ \
    && mkdir /etc/nginx/sites-enabled \
    && chown -R nginx.nginx /var/cache/nginx/ /var/www/ /run \
    && chown -R nginx.nginx /var/www/

COPY docker/server/config/nginx.conf /etc/nginx/nginx.conf
COPY docker/server/config/default /etc/nginx/sites-enabled
COPY --chown=nginx www/ /var/www/webpagetest
COPY docker/server/config/locations.ini /var/www/webpagetest/settings/locations.ini
COPY docker/server/config/connectivity.ini /var/www/webpagetest/settings/connectivity.ini
COPY docker/server/config/settings.tpl /var/www/webpagetest/settings/settings.tpl
COPY docker/server/config/mobile_devices.ini /var/www/webpagetest/settings/mobile_devices.ini

RUN chown -R nginx /var/www/webpagetest/settings/


USER nginx
EXPOSE 8080
CMD ["/bin/sh",  "-c",  "envsubst < /var/www/webpagetest/settings/settings.tpl > /var/www/webpagetest/settings/settings.ini && exec nginx -g 'daemon off;'"]
