FROM php:7.4-fpm-alpine
LABEL maintainer="Wolfgang Schiffels<wolfgang.schiffels@baqend.com>"

RUN apk add --no-cache supervisor beanstalkd imagemagick imagemagick-libs zip libzip \
    && mkdir -p /var/www/ \
    && mkdir -p /scripts

RUN apk add --no-cache --virtual .build-deps zlib-dev \
    libpng-dev jpeg-dev freetype-dev libzip-dev curl-dev autoconf gcc g++ \
    imagemagick-dev make \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && docker-php-ext-install curl \
    && printf "\n" | pecl install imagick \
    && docker-php-ext-enable imagick \
    && apk del --no-cache .build-deps

COPY docker/server/config/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
COPY docker/server/config/php.ini /usr/local/etc/php/

COPY docker/server/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/server/config/supervisord/supervisord_php-fpm.conf /etc/supervisor/conf.d/supervisord_php-fpm.conf
COPY docker/server/config/supervisord/supervisord_beanstalkd.conf /etc/supervisor/conf.d/supervisord_beanstalkd.conf
COPY docker/server/config/supervisord/supervisord_ec2init.conf /etc/supervisor/conf.d/supervisord_ec2init.conf

COPY --chown=nobody www/ /var/www/webpagetest
COPY docker/server/config/locations.ini /var/www/webpagetest/settings/locations.ini
COPY docker/server/config/connectivity.ini /var/www/webpagetest/settings/connectivity.ini
COPY docker/server/scripts/ /scripts/

COPY docker/server/config/periodic/15min/wpt_cron_call.sh /etc/periodic/15min/
COPY docker/server/config/periodic/hourly/wpt_cron_call.sh /etc/periodic/hourly/

RUN chmod 755 /scripts/* \
    && chown -R nobody.nobody /run

USER nobody
WORKDIR /var/www/webpagetest
EXPOSE 9000
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
