FROM nginx:alpine
LABEL maintainer="Wolfgang Schiffels<wolfgang.schiffels@baqend.com>"

RUN rm /etc/nginx/conf.d/default.conf \
    && mkdir -p /var/www/ \
    && mkdir /etc/nginx/sites-enabled \
    && chown -R nginx.nginx /var/cache/nginx/ /var/www/ /run \
    && chown -R nginx.nginx /var/www/

COPY docker/server/config/nginx.conf /etc/nginx/nginx.conf
COPY docker/server/config/default /etc/nginx/sites-enabled
COPY --chown=nginx www/ /var/www/webpagetest
COPY docker/server/config/locations.ini /var/www/webpagetest/settings/locations.ini
COPY docker/server/config/connectivity.ini /var/www/webpagetest/settings/connectivity.ini

USER nginx
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]
